### ISSUE TITLE
Question: can this potentially work with class-based stores?

### ISSUE THREAD

**Issue by bestguy** [episage/svelte-mobx-observer#1]
Project looks neat, but curious if this approach can potentially be used for class based stores with multiple observables, computeds, actions, etc?

**Comment by episage** [comment]
I think so. However, beware that this project doesn't work out of the box. For it to work you need a deep mobx-svelte integration as described here https://github.com/sveltejs/svelte/issues/5172#issuecomment-661849862 . I will work on it soon. Svelte is too good not to work with MobX

**Comment by episage** [comment]
I think I just finished the rewrite and it works. Please take a look at https://github.com/episage/svelte-mobx-observer
